{
 "title": "jwt-pizza-service",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "targets": [
    { "expr": "latency_response_time", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizza Revenue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pizza_total{method=\"revenue\"}",
     "legendFormat": "Pizza Revenue"
    },
    {
     "expr": "pizza_total{method=\"failures\"}",
     "legendFormat": "failures"
    },
    {
     "expr": "pizza_total{method=\"sold\"}",
     "legendFormat": "Pizzas Sold"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_count{method=\"active\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "CPU and Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_usage{method=\"memory\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "system_usage{method=\"cpu\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Pizzas Sold",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "pizza_total{method=\"sold\"}",
     "legendFormat": "Pizzas Sold"
    },
    { "expr": "pizza_failures_total", "legendFormat": "__auto" },
    {
     "expr": "pizza_total{method=\"failures\"}",
     "legendFormat": "Pizza Failures"
    }
   ]
  },
  {
   "title": "Authentication Attempts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "auth_attempts{method=\"success\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "auth_attempts{method=\"failure\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 13 },
   "targets": [
    { "expr": "request_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Requests by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "request_total{method=\"GET\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}